# config_version=4


hardware:
  driverboards: snux
  platform: p_roc

physical_dmds:
  dmd:
    shades: 16
    fps: 24

config:
- hardware.yaml
- shots.yaml
- keyboard.yaml
- sound.yaml

mpf:
  default_pulse_ms: 20

game:
  balls_per_game: 3
  max_players: 4

modes:
- base
#- skillshot
#- bonus
#- high_score
- tilt
- service
#  - credits

widget_styles:
  text_default:
    font_name: Quadrit
    font_size: 10
    adjust_top: 2
    adjust_bottom: 3
  space title huge:
    font_name: DEADJIM
    font_size: 29
    antialias: true
    adjust_top: 3
    adjust_bottom: 3
  space title:
    font_name: DEADJIM
    font_size: 21
    antialias: true
    adjust_top: 2
    adjust_bottom: 3
  medium:
    font_name: pixelmix
    font_size: 8
    adjust_top: 1
    adjust_bottom: 1
  small:
    font_name: smallest_pixel-7
    font_size: 9
    adjust_top: 2
    adjust_bottom: 3
  tall title:
    font_name: big_noodle_titling
    font_size: 20
